services:
  - type: web
    name: wms-postgres
    plan: free
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
